### ISSUE TITLE
min / max length filtering

### ISSUE THREAD

**Issue by pgtb** [a-slide/pycoQC#102]
First thanks a lot for your nice and useful tool !

I am just asking if is it possible to add a minimum (and maximum) read length as new filtering parameters. Could be useful to get a quick view of what we can real expect for target sequencing; amplicons sequencing etc.

thank you

all the best

**Comment by pgtb** [comment]
First thanks a lot for your nice and usefull tool !

I am just asking if is it possible to add a minimum (and maximum) read length as new filtering parameters. Could be usefull to get a quick view of what we can real expect for target sequencing; amplicons sequencing etc.

thank you

all the best

**Comment by a-slide** [comment]
I actually recently added an option for that: `--min_pass_len`
If you update to the latest version (2.5.0.14) it should be there.
Cheers

**Comment by pgtb** [comment]
OK

Thanks a lot for your quick reply !

best

--
Christophe Boury
Assistant Ingénieur (Lab Geek)
Plateforme Genome Transcriptome de Bordeaux
INRA - UMR 1202 BIOGECO
69 route d'Arcachon
33612 Cestas - Pierroton
FRANCE

05.35.38.53.36
christophe.boury@inra.fr<mailto:christophe.boury@inra.fr>
pgtb@inra.fr<mailto:pgtb@inra.fr>

https://pgtb.cgfb.u-bordeaux.fr/
https://twitter.com/pgt_bordeaux

De : Adrien Leger [mailto:notifications@github.com]
Envoyé : mardi 22 octobre 2019 10:15
À : a-slide/pycoQC <pycoQC@noreply.github.com>
Cc : pgtb <pgtb@inra.fr>; Author <author@noreply.github.com>
Objet : Re: [a-slide/pycoQC] min / max length filtering (#102)


I actually recently added an option for that: --min_pass_len
If you update to the latest version (2.5.0.14) it should be there.
Cheers
