### ISSUE TITLE
Cannot use alignment file as an input

### ISSUE THREAD

**Issue by lundlab-kaltinel** [a-slide/pycoQC#111]
I am trying to use pycoQC (`pycoQC v2.5.0.3` with `python 3.6` on `conda 4.7.12`) to have some quality control over my dataset, and it works well with the minimal option (when only working with sequencing summary input).
* Used minimal options:
`pycoQC -f sequencing_summary.txt -o pycoQC_output.html`

* When I wanted to use the primary reads only bam file as input:
`pycoQC -f sequencing_summary.txt -a sorted_Primary-Alignments.bam -o Primary_pycoQC_output.html`
This gave me the error of
` d["align_score"] = d["align_len"]/edit_dist
ZeroDivisionError: division by zero`

I thought it is because I only used the primary reads, so secondary reads are still existent in the sequencing summary file and therefore I am having these division by zero error. 

* Therefore, I tried to use the whole bam file ( sorted + indexed ), but I still receive the same error:
`pycoQC -f sequencing_summary.txt -a sorted_ALL.bam -o All_pycoQC_output.html`

* Error:

> Checking arguments values
Check input data files
Parse data files
Traceback (most recent call last):
  File "/home/bin/pycoQC", line 12, in <module>
    sys.exit(main_pycoQC())
  File "/home/bin/pycoQC/__main__.py", line 124, in main_pycoQC
    quiet = args.quiet)
  File "/home/bin/pycoQC/lib/python3.6/site-packages/pycoQC/pycoQC.py", line 123, in pycoQC
    quiet=quiet)
  File "/home/bin/envs/pycoQC/lib/python3.6/site-packages/pycoQC/pycoQC_parse.py", line 99, in __init__
    bam_reads_df, self.alignments_df, self.ref_len_dict = self._parse_bam()
  File "/home/bin/envs/pycoQC/lib/python3.6/site-packages/pycoQC/pycoQC_parse.py", line 207, in _parse_bam
    read_dict[read.query_name] = self._get_read_stats(read)
  File "/home/bin/envs/pycoQC/lib/python3.6/site-packages/pycoQC/pycoQC_parse.py", line 370, in _get_read_stats
    d["align_score"] = d["align_len"]/edit_dist
ZeroDivisionError: division by zero

I would appreciate to know how to get through this error.
Thank you!

**Comment by a-slide** [comment]
Hi @lundlab-kaltinel 

I believe that I fixed the bug a while ago but it looks like you are using an old version of pycoQC. I bet you installed it with conda and for some reason it does not install the last version. We are now on version 2.5.0.20.
To force conda to install the last version use the following command:
`conda install -c aleg pycoqc=2.5.0.20`

Otherwise pip always get the last one
`pip install pycoQC -U`

Let me know if it works
Cheers
Ad

**Comment by lundlab-kaltinel** [comment]
Hi,

Works well now! Thank you!
