### ISSUE TITLE
No module named 'pysam.libchtslib

### ISSUE THREAD

**Issue by ganiatgithub** [a-slide/pycoQC#116]
**Describe the bug**
Hi, I just started to work with pycoQC, I run into the error of "No module named 'pysam.libchtslib" when running pycoQC in jupyter notebook.

**To Reproduce**

> conda create -n pycoQC python=3.6
> conda activate pycoQC
> pip install pycoQC
> pip3 install notebook
> jupyter notebook

**Screenshots**

![Screen Shot 2020-05-05 at 9 58 40 pm](https://user-images.githubusercontent.com/50599499/81063746-c3cb7000-8f1b-11ea-9744-7acaf45fcfed.png)

**Desktop (please complete the following information):**

* OS: (OS X Mojavi)
* Browser (firefox)

**Additional context**
I did confirm that the package libchtslib is present at the system path that I feed to jupyter:

>(pycoQC) uqgni1-7329:pysam uqgni1$ ls /opt/anaconda3/envs/pycoQC/lib/python3.6/site-packages/pysam | grep "libchtslib"
>libchtslib.cpython-36m-darwin.so
>libchtslib.pxd

Any tips on trouble shooting?

Thank you!

**Comment by a-slide** [comment]
Hi @ganiatgithub 
I am not sure I can do anything about that, it seems to be a pysam library issue.
Can you tell me which version of pysam is installed in your environment ?

```
import pysam
pysam.__version__
```

Thanks

**Comment by ganiatgithub** [comment]
Hi, it is 0.15.3

**Comment by ganiatgithub** [comment]
As a matter of fact, I worked it out in command line, so you may close this now :)

**Comment by a-slide** [comment]
Great thanks
