### ISSUE TITLE
"run summary by barcode" section missing?

### ISSUE THREAD

**Issue by inijman** [a-slide/pycoQC#117]
Hi, it strikes me that in pycoQC 2.5.0.21 the section "run summary by barcode" is missing from the report while it was there in 2.3.1.6.

I really liked this overview as it exactly showed data not present in other reports.

Is there a way to reactivate this option?

**Comment by a-slide** [comment]
Hi @inijman,
Yes, I removed the feature in Nanocompore 2.5 and replaced it by a utility to split the summary sequencing file by barcode (https://a-slide.github.io/pycoQC/Barcode_split/usage/).
Then you get 1 report per barcode, which actually gets you much more insight into your data.
Then, a meta-report can be created with multiQC which now supports pycoQC (https://github.com/a-slide/pycoQC/issues/63)

I am also working on an internal command to create a meta-report within pycoQC.

Cheers

**Comment by inijman** [comment]
ah, too bad. With the barcodes going up to 96 it becomes quite a hassle and the previous overview where perfectly fine. I'll stick to v 2.3 then.
