### ISSUE TITLE
Output -Bam files  Phyton 3.7?

### ISSUE THREAD

**Issue by Francisjpll** [a-slide/pycoQC#118]
Dear a-slide

I am wondering if there is version of PycoQC that provides the output of the bam files  with Phyton =3.7.  I have tried pycoqc=2.5.0.20 which did not work with Phyton =3.7, it seems to work only with Phyton=3.6

Thank you in advance 

Johanna

**Comment by a-slide** [comment]
Hi,
Did you manage to fix the issue by yourself ?

**Comment by Francisjpll** [comment]
Yes, I managed

However,  I would like to ask if pycoQC can provide a representation of the alignment per each sample when you perform a multiplexed sample MinION run.

In my case, I have the summary sequencing txt file of a MinION run and six alignment.bam  files of six samples assessed in this run. These bam files were generated using Minimap2 (mapping to a reference genome approach)

I tried it as follows:

All samples

•	pycoQC -f runi0001_sequencing_summary.txt -a sample1_barcode01.bam sample2_barcode02.bam sample3_barcode03.bam sample4_barcode04.bam  sample5_barcode05.bam sample6_barcode06.bam -o runi0001_output.html

Each sample: 

•	pycoQC -f runi0001_sequencing_summary.txt -a sample1_barcode01.bam -o runi0001_output.html

When I do all the samples I see an increase in proportions in the alignment representation but it does not show from which indexed sample came from.

This is a really cool tool :) the visual representations are beautiful

Looking forward to hearing from you, 

Johanna

**Comment by a-slide** [comment]
Hi Johanna,

There used to be a functionality to display information for individual barcode that but it became too complicated with the BAM files so I decided to remove it. However, I added an extra command to split you summary files by barcode: https://a-slide.github.io/pycoQC/Barcode_split/usage/
Then you can run pycoQC for each pair of summary file/ Bam file.
If you want to bring some of the information together in a single report you can then use multiQC, which now supports pycoQC json files https://multiqc.info/docs/#pycoqc
