### ISSUE TITLE
pycoQC.common.pycoQCError: Invalid sequencing summary file

### ISSUE THREAD

**Issue by anastasiasatyr** [a-slide/pycoQC#119]
Hello,

I wanted to use pycoQC, my command was:

pycoQC --summary_file sequencing_summary_FAN01972_fd19c77f.txt -o output.html

and I received an error:

pycoQC.common.pycoQCError: Invalid sequencing summary file

The pycoQC version is : v2.3.1.6
The sequencing_summary.txt file was obtained from MinION sorfware of version 19.12.5

**Comment by a-slide** [comment]
Hi @anastasiasatyr,
Can you tell me how you generated the summary file and share the 10 first lines with me ?
Thanks

**Comment by anastasiasatyr** [comment]
Hey,

I have already solved my problem (yes it was the problem with unformatted lines in the summary file),

you can close the issue.
