### ISSUE TITLE
Can not install pycoQC (version 2.5.0.21) in anaconda

### ISSUE THREAD

**Issue by xlinxlin** [a-slide/pycoQC#120]
Hi!

I have a problem by installing pycoQC (version 2.5.0.21) in an anaconda environment.
First it told me "ResolvePackageNotFound"
```
(nxf-ont) yan@xps13:~$ conda install -c bioconda pycoqc=2.5.0.21
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound: 
  - tqdm=4.35.0

```
After I installed it by using command `conda install -c conda-forge tqdm=4.35.0` then I ran `conda install -c bioconda pycoqc=2.5.0.21` again, but unfortunately failed again:
```
(nxf-ont) yan@xps13:~$ conda install -c bioconda pycoqc=2.5.0.21
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
If I run `conda install -c bioconda pycoqc` without specific version it will install pycoQC version 2.2.3, but I need 2.5.0.21 because I had the same issue described in https://github.com/a-slide/pycoQC/issues/112

OS: Ubuntu 16.04

Could you help me with this? Thanks a lot!

**Comment by xlinxlin** [comment]
The environment was created by using the command `conda create -n nxf-ont python=3.6`

**Comment by xlinxlin** [comment]
I have also tried with the channel `aleg`

```
(nxf-ont) yan@xps13:~$ conda install -c aleg pycoqc=2.5.0.21
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by a-slide** [comment]
Hi @xlinxlin,

I assume conda forge and bioconda are not in your default conda repositories ?

Can you try the following in a newly created clean python 3.6 or 3.7 environment:
`conda install -c aleg -c conda-forge -c bioconda pycoqc=2.5.0.21`

Otherwise, just try with pip instead

**Comment by xlinxlin** [comment]
> Hi @xlinxlin,
> 
> I assume conda forge and bioconda are not in your default conda repositories ?
> 
> Can you try the following in a newly created clean python 3.6 or 3.7 environment:
> `conda install -c aleg -c conda-forge -c bioconda pycoqc=2.5.0.21`
> 
> Otherwise, just try with pip instead

With your command it works,, thanks!
