### ISSUE TITLE
Summary breakdown by runID within one sequencing summary file? 

### ISSUE THREAD

**Issue by callumparr** [a-slide/pycoQC#122]
I remember previous version breaking down summary by runIDs when multiple runs are basecalled together within one sequencing summary file. But I after updates I cannot seem to get this output anymore? I can see with verbose log the runIDs are identified. 

Is this still possible?

**Comment by a-slide** [comment]
Hi @callumparr,
I think I got rid of that a while ago now unfortunately
I guess you can still manually split the seq summary by run id if you want to and run pycoQC on the resulting files.

**Comment by callumparr** [comment]
Ah yeh I can do that! Thank you.

**Comment by fo40225** [comment]
I think the output of the following charts should be separated by run-id. Combining the run-ids results in unreasonable charts.
- Output over experiment time
- Read length over experiment time
- Read quality over experiment time
- Aligned reads length over experiment time
- Aligned reads identity over experiment time
