### ISSUE TITLE
Cannot install pycoQC on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by michielmuliergithub** [a-slide/pycoQC#123]
<h3>1. Bug description</h3>

Installing `pycoQC` on my new `Ubuntu 20.04.1 LTS` system fails. I'll go through the steps I took and elaborate on the failure in the end.

First I install some software that `pycoQC` apparently needs:
```sh
$ sudo apt-get install libbz2-dev
$ sudo apt-get install liblzma-dev
$ sudo apt-get install libblas-dev
$ sudo apt-get install liblapack-dev
```

Next I install all the required python packages:
```sh
$ sudo pip3 install numpy
$ sudo pip3 install pandas
$ sudo pip3 install pysam
$ sudo pip3 install scipy
```

Finally, I issue the command to install `pycoQC`:
```sh
$ sudo pip3 install pycoQC
```

I get a lot of output, with the following error lines:
```sh
[..]
Building wheel for pandas (setup.py) ... error
[..]
Building wheel for numpy (setup.py) ... error
[..]
Building wheel for pysam (setup.py) ... error
[..]
Building wheel for scipy (PEP 517) ... error
[..]
Failed to build pandas numpy pysam scipy
```

<h3>2. What I've tried</h3>

`Ubuntu 20.04.1 LTS` natively has Python 3.8. I was worried that `pycoQC` might not yet be tested on such a recent Python version, leading to the failure. Therefore, I installed a Python 3.6.0 virtual environment to try the `pycoQC` installation again. Unfortunately, this didn't help.

<h3>3. Console output</h3>

When trying the second time (with Python 3.6.0) I logged all the console output to a file:

[error_output.txt](https://github.com/a-slide/pycoQC/files/5506463/error_output.txt)

Please check this error output. Hopefully it helps to fix the installation bug.

**Comment by a-slide** [comment]
Hi @michielmuliergithub,
You should not need to install any dependencies if you use pip or conda.
Can you just try `pip install pycoQC==2.5.0.23` in a fresh python3.6 virtual environment ?
What sort of virtual env manager do you use ?

**Comment by michielmuliergithub** [comment]
Hi @a-slide ,
Thank you very much. It worked!

I first installed Miniconda (see https://docs.conda.io). Then I issued the following commands:

```sh
$ conda create -n pycoQC python=3.6
$ conda activate pycoQC
$ conda install -c bioconda pycoqc
$ pycoQC --version
    pycoQC v2.2.3
```

Thank you very much!
Kind regards,
Michiel Mulier

**Comment by a-slide** [comment]
Great
By default the bioconda version is installed, but it is quite outdated.
To get the last stable version use my personal channel instead

```conda install -c aleg pycoqc=2.5.0.23```

**Comment by nbeckloff** [comment]
Hi @a-slide ,
   I tried to install pycoQC 2.5.0.23 using both the conda and pip commands above but both produced errors. When using the conda command above I received this error:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

  and when trying the PIP installer I received errors in the txt (piperror.txt).

  I'm running Ubuntu 20 on a WLS.
[piperror.txt](https://github.com/a-slide/pycoQC/files/5591439/piperror.txt)

Thanks in advance,
cheers,
  Nick

**Comment by a-slide** [comment]
Hi @nbeckloff, 
Have you tried to install the package in a virtual environment as recommended in the documentation? 
```
conda create -n pycoQC python=3.6
conda activate pycoQC
conda install -c aleg pycoqc=2.5.0.23
```

**Comment by nbeckloff** [comment]
Hi @a-slide,
  Ultimately, I was able to get it installed, there was an errant dependency issue that I had to fix manually. 
  Thanks for your help and great program!

cheers,
  Nick

**Comment by michielmuliergithub** [comment]
Thank you very much

It worked to install pycoQC

Michiel Mulier






Op zo 8 nov. 2020 om 16:26 schreef Adrien Leger <notifications@github.com>:
