### ISSUE TITLE
Add command line interface with a config file that generates an HTML report

### ISSUE THREAD

**Issue by a-slide** [a-slide/pycoQC#19]

**Comment by tleonardi** [comment]
Still happy for me to take care of this? If so, I'm on it!

**Comment by a-slide** [comment]
So I was trying to assign you but fail 2 times in a row... I am still happy if you want to do it
Ideally it will come with a configuration file to parameter all the functions, with https://docs.python.org/3/library/configparser.html for exemple.

**Comment by a-slide** [comment]
iplot==False instantiate pycoQC in a way that plotting functions only return a plotly Figure object

**Comment by a-slide** [comment]
Actually ... https://plot.ly/python/html-reports/
It might be easier to starts there

**Comment by a-slide** [comment]
Prototype done
