### ISSUE TITLE
Clarification regarding 1D2 vs 2D run

### ISSUE THREAD

**Issue by TheChymist** [a-slide/pycoQC#3]
The introductory information refers to the Albacore output of a "2D" run. However this is the tabular output from 1D2 reads. The previous 2D output tables were quite different. See attached file for 2D column names.
[2D_column_headers.txt](https://github.com/a-slide/pycoQC/files/1218165/2D_column_headers.txt)

**Comment by a-slide** [comment]
Hi Mike,
Thanks for raising the problem. I have to clarify this point indeed and separate 1D2 and 2D (even though 2D will be completely dropped apparently). Could you provide a test file for a 2D run with 10000+ lines ?
Thanks

**Comment by a-slide** [comment]
Hi Mike,
I think I will drop the 2D support in the next release as it is not supported by ONT any more, and I don't think people are still using it nowadays.
Cheers

**Comment by TheChymist** [comment]
Yeah that's fine, my original point was where the documentation said "2D" it actually was referring to 1D2. 
Nb: Since there was never actually support for input of 2D tables, nothing will change. Though you can play with the old 2D output to make it work with the pycoQC 1D2 functionality.

**Comment by a-slide** [comment]
Sure thanks.
I am updating the package at the moment so if you have any idea of functionality that could be useful don't hesitate to raise an other issue.
