### ISSUE TITLE
import sys addition

### ISSUE THREAD

**Issue by drknnetz** [a-slide/pycoQC#4]
I know this is a tutorial, and you are using a dataset designed for the tutorial, but it may be worth including a section in the workflow about using a real dataset. It is an easy addition and I know these manuals are often designed for people who understand the code but it may be useful for people who aren't great at coding to include a portion in the readme:
after:
from pycoQC.pycoQC import jprint as print
import sys
example_file_1D = '/path/to/real/sequencing/sequencing_summary.txt'
print(example_file_1D)
/path/to/real/sequencing/sequencing_summary.txt
Then all analysis following this portion will point to real data rather than your preloaded set. I only say this because I have had this installed in my work's cluster and I have had several people ask me why they always get the same output for the data. I then refer them to this or meet with them to show them but it makes it more inclusive.
Thanks

**Comment by a-slide** [comment]
Hi Dennis,

Thanks for raising the issue, I will clarify it in the next release, that should be coming soon.
Happy to see that people are actually using it.

Cheers
