### ISSUE TITLE
Add Guppy barcoding information to plots

### ISSUE THREAD

**Issue by daanverhagen** [a-slide/pycoQC#40]
Demultiplexed files from Guppy are concatenated in one large text file: barcoding_summary.txt. Current pycoQC can not handle this file

Guppy barcoding summary test file (50.000 random reads):

[barcoding_summary_test.txt](https://github.com/a-slide/pycoQC/files/2773019/barcoding_summary_test.txt)

**Comment by a-slide** [comment]
Thanks a lot Daan. It looks fairly trivial to merge the 2 files. Would you mind providing the summary sequencing file that goes with it thought ?
Thanks

**Comment by daanverhagen** [comment]
heres the associated sequence_summary.txt file. Because the barcoding_summary file are the first 50.000 lines of the file, i dont know the same reads IDs are accounted for in the sequence_summary file. If theres any problems with coverage or something can send you a link to the full files


[sequencing_summary_test.txt](https://github.com/a-slide/pycoQC/files/2778302/sequencing_summary_test.txt)

**Comment by a-slide** [comment]
It should update to version v2.1a8

**Comment by daanverhagen** [comment]
I cant download the dev version. perhaps im doing something wrong but i get an error that my permission is denied (publickey), that it cant read from the repository and an error code in None. latest version i could pull is v2.1a7.

**Comment by a-slide** [comment]
Ah sorry I assumed you had a ssh key set up for github. Try that instead:

`pip install git+https://github.com/a-slide/pycoQC.git@dev -U`

**Comment by daanverhagen** [comment]
alright i was able to upgrade tov2.1a8. running it with barcoding_summary.txt did not work. running it with sequencing_summary.txt does, but again (obviously) no barcoding information is in there. What file or files do you use to add barcoding information?

`pycoQC -f ~/Documents/sequencing_summary.txt -o ~/Documents/out.html
`
Is what i used but i might need to add barcoding_summary.txt somewhere here?

**Comment by a-slide** [comment]
The help message should mention the new option  `-b`
So the command line should now be:

`pycoQC -f ~/Documents/sequencing_summary.txt  -b ~/Documents/barcoding_summary.txt  -o ~/Documents/out.html `

Let me know if this is not the case.

**Comment by a-slide** [comment]
Try running it with `--verbose_level 2` to check how many reads with barcodes are found

**Comment by daanverhagen** [comment]
alright seems to work great now with the -b option 

![pyco barcode output](https://user-images.githubusercontent.com/44024365/51747874-fcd72c80-20aa-11e9-8466-0755486dbfb8.png)

out of 1.77M reads 1.69M are found with barcodes. Thanks for the help

**Comment by a-slide** [comment]
Awesome. Let's close the issue then

**Comment by a-slide** [comment]
Hi Dann,
Would you mind if I include a sample of the files you sent me (10000 reads) as an example dataset in pycoQC ?
If so you will be acknowledge in the package documentation.
Thanks

**Comment by daanverhagen** [comment]
Sure, no problem.
