### ISSUE TITLE
Add support for multi-fast5 to Fast5_to_seq_summary

### ISSUE THREAD

**Issue by a-slide** [a-slide/pycoQC#49]
Recent versions of minknow/Guppy use multi-fast5 format (multiple reads per files).
Fast5_to_seq_summary is not compatible with this format at the moment

**Comment by huyustats** [comment]
Hi,

I wonder whether the newest version can deal with multiple reads per file?

Thanks

**Comment by a-slide** [comment]
Nope. I did not know if people were interested in the feature.

**Comment by a-slide** [comment]
https://github.com/a-slide/pycoQC/pull/121
