### ISSUE TITLE
Integration with multiQC

### ISSUE THREAD

**Issue by a-slide** [a-slide/pycoQC#63]
Would be nice to have a report text mode only for integration in multiQC

**Comment by a-slide** [comment]
Added json output that could be use for integration in multiQC
https://github.com/a-slide/pycoQC/commit/eef783b6646c2d9ee850ad69886ae88373a357ea

**Comment by csawye01** [comment]
Hello, I can't see the way to output this json file in the documentation and it isn't automatically output when I use this program. How do you specify this output?

**Comment by csawye01** [comment]
@a-slide The json output may not work as it doesn't have all of the plot points to recreate the graphs within to use in a multiQC module. Would it be possible to output all the points for each of the graphs instead of just the C1, D1, median, etc? It may be easier to create a MultiQC Module with that instead.

**Comment by a-slide** [comment]
Hi @csawye01,
In the latest version of pycoQC, the json file contains all the 100 percentiles for the different distributions (basecall length, PHRED quality, align length and %identity). It saves a lot of space compared with outputting all the data point.
If you plot the series with a density function (ie Seaborn violin-plot) you get a good approximation of the original distribution, although it is a bit smoothed.

Here is a snippet in Python3 I use in Jupyter:
```
import json
import pandas as pd
import glob
import os
import matplotlib.pyplot as pl
import seaborn as sns
%matplotlib inline

# Collect data for all samples in a dictionnary
res_dict = {}
for fn in glob.glob ("./results/pycoqc/*.json"):
    sample_id = os.path.split(fn)[1].split("_")[0]
    with open (fn) as fp: 
        all_res = json.load(fp)
        res_dict[sample_id] = all_res['All Reads']["basecall"]["len_percentiles"]

# Cast to dataframe
res_df = pd.DataFrame.from_dict(res_dict, orient="columns")
display(res_df)

# Plot a violin plot with plotly
fig, ax = pl.subplots(figsize=(20, 10))
sns.violinplot(data=res_df, palette="viridis", ax=ax, cut=0, bw=0.1)
_ = ax.set_ylim(0, 20000)
_ = ax.set_title("Alignment length distribution across samples")
```

![Screenshot_2019-11-26 Post_QC - Jupyter Notebook](https://user-images.githubusercontent.com/5701192/69649478-03388b00-1065-11ea-8145-210a7ca5d120.png)

**Comment by csawye01** [comment]
Oh ok, thanks so much!

**Comment by ewels** [comment]
Hi @a-slide,

I appreciate that the JSON file could get pretty huge if you dump all plot data into it. However, the profile of certain plots such as _Distribution of read length_ can be interesting and the medians / quartiles can miss this. For example:

![image](https://user-images.githubusercontent.com/465550/69653339-56b1d580-1073-11ea-845f-22724cd024ca.png)

Would it be possible for pycoQC to dump all plot data to a separate file? That way the basic metrics JSON file stays clean, but it's also possible to re-plot the data in other applications such as MultiQC.

Cheers,

Phil

**Comment by a-slide** [comment]
Hi @ewels,
It's not just the median and quartiles, it's all the percentiles (100 values)
Would you mind testing the method I gave to @csawye01 with this dataset ? I bet it will be much smoother, but if the point is to quickly compare multiple runs it might do the trick.
Cheers

**Comment by ewels** [comment]
Ah, apologies. When I read percentiles I assumed every 10th percentile for some reason (I guess quite a lot of other tools do this). 100 will be a little blocky but might do the job, I’ll take a look.

**Comment by ewels** [comment]
Ah, the example report I'm looking at is from pycoQC version `2.2.3.7` - which is probably the other reason why I didn't realise that there were 100 values! I get the following:

```json
      "Read length quantiles": {
        "Min": 147.0,
        "C1": 251.23000000000002,
        "D1": 615.0,
        "Q1": 2503.0,
        "Median": 3741.0,
        "Q3": 4083.0,
        "D9": 4119.0,
        "C99": 17326.21999999977,
        "Max": 47930.0
      },
```

@csawye01 - do you think you could re-run this sample again with the latest release of pycoQC please?

**Comment by a-slide** [comment]
Let me know if this is enough, otherwise I can increase the granularity,
As I pointed out before the report contains distributions for basecall length, PHRED quality, align length and %identity. The new format is also better organised and contains additional extra information. Here is the basic format
 
```
run
    run_duration
    active_channels
    runid_number
    barcodes_number
basecall
    reads_number
    bases_number
    N50
    len_percentiles
    qual_score_percentiles
# Additional section if alignment information provided
alignment
    reads_number
    bases_number
    mean_coverage
    N50
    len_percentiles
    # Additional section if identity information parsed from BAM (NM of MD tag)
    identity_freq_percentiles
    insertion_rate
    deletion_rate
    mismatch_rate
```

**Comment by csawye01** [comment]
Is the current Bioconda package available have the latest version with these changes?

**Comment by a-slide** [comment]
Hi @csawye01 and @ewels,
May I have an update on pycoQC integration ?
Cheers
Ad

**Comment by ewels** [comment]
Hi @a-slide,

By coincidence, @ssjunnebo and I have been looking at this again today. The general parsing code and output of tabular data is coming along nicely thanks to @ssjunnebo and I was taking a look at the plot data.

To cut a long story short, I struggled to reproduce the nice histogram plot that you have in the original pycoQC report. Your code snippet worked beautifully and I had a long conversation with @winni2k about how kernel density estimation works, however the problem is that MultiQC doesn't currently import `seaborn` / `scipy` / `pyqt` or any other packages that can have [stats functions](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) for this problem.

Whilst of course I could add one of these in, I am very hesitant about adding any new dependencies to the codebase due to painful past experiences with the large user base, especially if it is only needed for a single plot / module.

If you have any code suggestions for how we can reproduce the _Basecalled reads length_ plot and others from this data without using any new dependencies, that would be great (stats is not my greatest strength!). Otherwise I think I will have to give them a miss I'm afraid.

Phil

**Comment by winni2k** [comment]
I know KDE's are cool, but how about a histogram? Numpy and matplotlib offer the the `hist` function?

**Comment by a-slide** [comment]
Hi both
I guess a basic matplotlib boxplot would work well, although without the fine granularity of a violinplot.
All the distribution plots in pycoQC use a KDE like function, and I guess there are no ways around if you want the exact same kind of output. Another way might be to draw the distribution based on the knowledge that the pycoQC report actually contains the values for all of the 100 percentiles instead of the real values.

Ad

**Comment by ewels** [comment]
Is it not possible to just dump the exact plot values that pycoQC uses for the plotly graph? The `x` and `y`
values from here:
https://github.com/a-slide/pycoQC/blob/7a9077c694d89b00c38621155f05c14e9f5ed2a9/pycoQC/pycoQC_plot.py#L528-L533

Then I can just exactly replicate the plots in MultiQC without having to do anything to the numbers.

Phil

**Comment by a-slide** [comment]
Well yes, It is precomputed density coordinates. I guess it would be possible to include the sames values in the report. 
Are you thinking of stacking the density plots for multiple samples ? 
Ad

**Comment by ewels** [comment]
Yup, that was my intention. Generally I try to replicate original tool output as closely as I can for MultiQC so that users familiar with the tool immediately recognise the outputs.

Phil

**Comment by a-slide** [comment]
Alright done!
The new version of pycoQC (2.5.0.20) outputs extra fields in the JSON report.
It returns the same kind of data as generated by pycoCQ density plots. Essentially for each plots, you get a set of smoothed  X/Y coordinates that can be used to plot a distribution. I kept the percentile data in the report as well, so it is also quite easy to get the median, quartiles, deciles...
Please note that the alignment section of the report is only available if pycoQC was run with a bam file. 

Here is a Jupyter code snippet to generate density mapping using matplotlib only

```
import json
import matplotlib.pyplot as pl
%matplotlib inline

with open ("./results/sample_2.json") as fp:
    j = json.load(fp)

# For basecalling quality score
fig, ax = pl.subplots(figsize=(20, 5))
x = j["All Reads"]["basecall"]["qual_score_hist"]["x"]
y = j["All Reads"]["basecall"]["qual_score_hist"]["y"]
median = j["All Reads"]["basecall"]["qual_score_percentiles"][49]
ax.set_title("Basecall Quality Score Histogram")
ax.fill_betweenx(y,x)
ax.axvline(median, c="0.2", ls="--")

fig, ax = pl.subplots(figsize=(20, 5))
x = j["All Reads"]["alignment"]["len_hist"]["x"]
y = j["All Reads"]["alignment"]["len_hist"]["y"]
median = j["All Reads"]["alignment"]["len_percentiles"][49]
ax.set_title("Align Length Histogram")
ax.fill_betweenx(y,x)
ax.set_xscale("log")
ax.axvline(median, c="0.2", ls="--")
```
**Output plot**

![len_hist](https://user-images.githubusercontent.com/5701192/74160113-d08a4180-4c14-11ea-8b06-a4f15625adc1.png)
![qscore_hist](https://user-images.githubusercontent.com/5701192/74160120-d122d800-4c14-11ea-9df6-90bfc86d532f.png)

**Example of new json reports**
[new_json.zip](https://github.com/a-slide/pycoQC/files/4181248/new_json.zip)

I hope this will do.

Cheers

Ad

**Comment by ewels** [comment]
Hi @a-slide,

Sorry for the lack of responses on this issue, and many thanks for the new output - this is perfect!

@ssjunnebo has now finished this MultiQC module and it’s merged into v1.9dev so will come out in the next release 👍🏻

Thanks again, and shout if you have any feedback / suggestions for the MultiQC module!

Phil

**Comment by a-slide** [comment]
Awesome.
Thanks @ssjunnebo and @ewels.

https://github.com/ewels/MultiQC/issues/1075

![Screenshot_2020-05-18 MultiQC Report](https://user-images.githubusercontent.com/5701192/82195948-f5b3dd80-98f0-11ea-957b-eb34da9ad3d1.png)

**Comment by a-slide** [comment]
At some point in a near(ish) future I will be adding a functionality to compare multiple run into pycoQC directly. See https://github.com/a-slide/pycoQC/issues/97 
I will keep you posted in case you would like to reuse the code base to generate similar plots for multiQC.

**Comment by ewels** [comment]
Great, sounds good!

Note that your screenshot above is a little out of date. Here's a current example report: [multiqc_report.zip](https://github.com/a-slide/pycoQC/files/4643326/multiqc_report.zip)

![multiqc_report.html](https://user-images.githubusercontent.com/465550/82199755-6b727600-98fe-11ea-976d-ee22447de67b.png)

**Comment by a-slide** [comment]
Oh very good, I did not see that. Good job guys

**Comment by ghausiabegum** [comment]
> Awesome.
> Thanks @ssjunnebo and @ewels.
> 
> [ewels/MultiQC#1075](https://github.com/ewels/MultiQC/issues/1075)
> 
> ![Screenshot_2020-05-18 MultiQC Report](https://user-images.githubusercontent.com/5701192/82195948-f5b3dd80-98f0-11ea-957b-eb34da9ad3d1.png)

This is what I am looking for. I have seven html reports from pycoQC. How do I load them into multiQC?
Thanks!

**Comment by a-slide** [comment]
You cannot load the HTML reports into MultiQC, you have to generate json reports with pycoQC (option `--json_outfile`) using the following naming convention `{sample-id}_pycoqc.json`
Then just run MultiQC on the folder containing the json reports

**Comment by ghausiabegum** [comment]
Thank you! It worked!
