### ISSUE TITLE
numpy.dtype size changed

### ISSUE THREAD

**Issue by thierryjanssens** [a-slide/pycoQC#64]
**Describe the bug**
Upon running the following code an error is reported.

bsub -q bio -o pycoQClog.txt -e pycoQCerror.txt -n 13 pycoQC -f fastq/sequencing_summary.txt  -o pycoQC_output.html

path/to/envs/pycoqc/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
path/to/envs/pycoqc/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed
[sequencing_summary.txt](https://github.com/a-slide/pycoQC/files/3120837/sequencing_summary.txt)
, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
path/to/envs/pycoqc/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning:

numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

**Comment by a-slide** [comment]
Hi Thierry,
Apparently, this can happen when you import scipy (or another package) that was compiled against an older numpy than is installed. [See there] (https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility)

Did you install pycoQC in a fresh virtual environment with conda or virtenvwrapper ?
Thanks
Ad

(I will take care of the other issue ASAP but I am a bit snowed under at the moment)

**Comment by thierryjanssens** [comment]
Hi Adrien,

I have solved it by recreating a fresh conda environment. (I suspect that the migration from anaconda to miniconda might have solved this...?).
The other issue on the alternative barcode set is still pending and is not solved by the new conda environment.
Thanks.

Thierry
