### ISSUE TITLE
summary of read stats per barcode

### ISSUE THREAD

**Issue by inijman** [a-slide/pycoQC#65]
HI,

Awesome tool, thanks!

What I would like to see though is the readlength stats, N50 and quality etc split out per barcode. Now this is done per summary file, but an option to recalculate all the readsstats per barcode would be great.

**Comment by a-slide** [comment]
Thanks,
I could eventually add an option to display data by runid or by barcode ?

**Comment by inijman** [comment]
That would indeed be awesome!

Gr ies Nijman

**Comment by a-slide** [comment]
I just pushed a bleeding edge version which gives you a general summary table (summary) a detailed runid summary (run_id_summary) and a barcode summary table (barcode_summary). All the tables are automatically included in pycoQC report if called through the command line.

![Screenshot from 2019-05-02 17-09-18](https://user-images.githubusercontent.com/5701192/57129193-96d70100-6d8d-11e9-9d5a-37922edb1cf8.png)

Could you please try the fix yourself and let me know if it works for you ?
The appropriate version can be installed with : 
```pip install git+https://github.com/a-slide/pycoQC.git@a60f2c6025f43431833237c26650e2aeb67fb364 --upgrade```

**Comment by inijman** [comment]
This is brilliant, thanks so much for the quick implementation. The results are identical with mine (in terms of read/base counts per barcode overall).

![image](https://user-images.githubusercontent.com/6938284/57137421-1fff2f80-6db0-11e9-809e-669ad24ba5ba.png)

**Comment by a-slide** [comment]
You are welcome. I think I will also add a barcode frequency cuttoff as for barcode_counts to remove low frequency randomly detected  barcodes   
I have a few other updates I want to implement and then I will make a new stable release including the new summary functions.
Cheers

**Comment by a-slide** [comment]
On top of other modifications I also added the ability to filter low abundance barcode (`--min_barcode_percent`)

```pip install git+https://github.com/a-slide/pycoQC.git@eef783b6646c2d9ee850ad69886ae88373a357ea --upgrade```

**Comment by a-slide** [comment]
Now available in stable version 2.2.4.0 icluding through pypi

**Comment by baracus37** [comment]
Hi,

I was looking for a feature like this, but on v2.5.0.17 I only get a pie chart with no. of reads per barcode. The summary file is from MinKnow 19.12.2.
It would be really helpful to get run stats per barcode. Or do I need to implement a special option? I could not find anything. I am running:

`pycoQC -f -o --report_title`

**Comment by a-slide** [comment]
Hi @baracus37,
I intentionally removed it in the last version as I added a function to split a sequencing summary per barcode. https://a-slide.github.io/pycoQC/Barcode_split/CLI_usage/
From there you can run pycoQC on each independent summary sequencing file and you will get report per barcode.

**Comment by baracus37** [comment]
Hi,

thanks for the information. I think I will then roll back to v2.3.1.6, as splitting the summary file per barcode and then run pycoQC individually on every barcode summary files is quite inconvenient compared to just running pycoQC on the original summary file.
