### ISSUE TITLE
Cannot write seq_summary_fn

### ISSUE THREAD

**Issue by apeltzer** [a-slide/pycoQC#68]
**Describe the bug**
I tried creating a report using a FAST5 folder inside a Docker container.

**To Reproduce**

1.) Use `nfcore/bacass:dev` container with pycoQC recipe in it.
2.) Try running `Fast5_to_seq_summary -f FAST5 -s testme`

```
Fast5_to_seq_summary -f FAST5 -s testme
Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-bacass-1.1.0dev/bin/Fast5_to_seq_summary", line 12, in <module>
    sys.exit(main_Fast5_to_seq_summary())
  File "/opt/conda/envs/nf-core-bacass-1.1.0dev/lib/python3.6/site-packages/pycoQC/cli.py", line 80, in main_Fast5_to_seq_summary
    verbose_level = args.verbose_level)
  File "/opt/conda/envs/nf-core-bacass-1.1.0dev/lib/python3.6/site-packages/pycoQC/Fast5_to_seq_summary.py", line 114, in __init__
    raise pycoQCError ("Cannot write the indicated seq_summary_fn")
pycoQC.common.pycoQCError: Cannot write the indicated seq_summary_fn
```

Though the directory is writable from inside the container without issues.

```
touch test_seq
(base) root@083663bc4c59:/home/apeltzer/bacass_test/work/7b/b16ef3592d07d01f0febf80be61d67# ls
FAST5  barcode01_NB01_Burkholderia.fastq  test_seq
```

**Expected behavior**
I expect the file to be written out :-) 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] CentoS7

**Comment by apeltzer** [comment]
Of course, feel free to ask if there are more questions!

**Comment by a-slide** [comment]
Hi Alexander
It looks like some kind of container environment insulation issue. I am not a specialist though.
Can you generate to file if you try Fast5_to_seq_summary from outside of the container ?
Which version of pycoQC are you using ?

**Comment by apeltzer** [comment]
I am using the latest one available from bioconda. (2.2.3, https://bioconda.github.io/recipes/pycoqc/README.html) . Didn't try to do that yet...

**Comment by a-slide** [comment]
Is it fixed ?

**Comment by apeltzer** [comment]
Sorry, I was on vacation - will hopefully get my hands on this in the next days again 👍 I will reply with feedback and try it manually... though I'm kind of hoping to get it working inside a container as thats the "shippable" solution for all our environments / clusters /cloud ....

**Comment by a-slide** [comment]
Just so you know pycoQC packages are now always up to date on pypi and anaconda thanks to continuous integration with Travis
pypi : https://pypi.org/project/pycoQC/
conda : https://anaconda.org/aleg/pycoqc

**Comment by apeltzer** [comment]
That means I will try this out now on some new data 👍
