### ISSUE TITLE
Compatibility with deepbinner classification file

### ISSUE THREAD

**Issue by mbhall88** [a-slide/pycoQC#69]
**Is your feature request related to a problem? Please describe.**
pycoQC is only compatible with guppy barcoder classification files.

**Describe the solution you'd like**
The ability to pass a barcode classification file from [deepbinner](https://github.com/rrwick/Deepbinner).

**Comment by a-slide** [comment]
Should be simple to implement.
Would you be able to provide a barcode classification file obtained with deepbinner as well as the corresponding sequencing summary file ?

**Comment by mbhall88** [comment]
This data is 4000 reads from a much bigger sample. If you want the full thing (summary file is 860Mb) then let me know and I can point you at it on the EBI cluster.
[classifications.subset.txt.gz](https://github.com/a-slide/pycoQC/files/3233427/classifications.subset.txt.gz)
[sequencing_summary.subset.txt.gz](https://github.com/a-slide/pycoQC/files/3233428/sequencing_summary.subset.txt.gz)

**Comment by a-slide** [comment]
Done in dev branch.
It took me a bit of time as I also refactor pycoQC to be more modular.
Could you try the modified version and let me know if it behave as you wanted?

`pip install git+https://github.com/a-slide/pycoQC.git@785f54c58b358660319872cb9054f4849882a653 --upgrade`

Thanks

**Comment by mbhall88** [comment]
Seems to be working fine. Here is the report I produced. As long as this looks as you expect then I would say it is working.

[madagascar_tb_controls_5.pycoqc.html.gz](https://github.com/a-slide/pycoQC/files/3330955/madagascar_tb_controls_5.pycoqc.html.gz)

**Comment by a-slide** [comment]
Great. I will roll the functionality in with the next release.
