### ISSUE TITLE
Export tables from report as *.tsv.

### ISSUE THREAD

**Issue by thierryjanssens** [a-slide/pycoQC#76]
**Is your feature request related to a problem? Please describe.**
The results in the tables (made by plotly) are enlocked in the *.html file.

**Describe the solution you'd like**
A button/handle in order to save the tabular results.

**Describe alternatives you've considered**
Looking into the source.

**Additional context**
N.A.

**Comment by a-slide** [comment]
Hi Thierry,
There is an option in pycoQC to export summay data in json (--json_outfile).

But I suspect you are more interested in data corresponding to individual plots.
In that case I recommend to use jupyter pycoQC API instead: https://a-slide.github.io/pycoQC/demo/pycoQC_API_demo/
Each PycoQC plotting function actually returns a plotly object containing the data use for the plots
Then for example if you want the data corresponding to the plot "len_over_time"

```
p  = pycoQC ("path_to_summary_file")
g = p.len_over_time ()
```

Then the data can be obtained interactively from the plotly object 
```g.data```

Each plot has a different way to represent the data so you you have to dig into the object to get what you want.

Now when using the API you also have a additional **_Edit chart_** button at the bottom of each plot which allows you to getthe data from plotly.ly website. Unfortunately the button is not supported in the standalone HTML document generated by the CLI. 

![Selection_004](https://user-images.githubusercontent.com/5701192/61722751-c3822f80-ad62-11e9-8857-8c9d5d229e49.png)
