### ISSUE TITLE
Add fastq support

### ISSUE THREAD

**Issue by mbhall88** [a-slide/pycoQC#79]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Be able to pass a fastq file as input rather than a sequencing summary file.

**Describe alternatives you've considered**
Using other tools? But their plots and reports aren't as nice as yours.

**Additional context**
I think a big use case for this is when I demultiplex a sample I have a bunch of single fastq files and it would nice to be able to see the quality metrics for just these.  
Additionally, I don't always have the sequencing summary file for a fastq.

**Comment by a-slide** [comment]
Hi Michael,

I don't plan to implement a fastq support in pycoQC as it doesn't contain all the info you can find in the seq summary file. I might implement something splitting the reads by barcode from the sequencing summary file maybe. But at the moment it is not on the top of my list. I quick hack would be to split your sequencing summary file manually before running pycoQC.
If you want to get your hands dirty I would be happy to accept a PR.

Thanks

**Comment by a-slide** [comment]
There is a now a function to split the sequencing summary by barcodes. It is still in dev in the branch BAM but I will merge it soon. At the moment it only supports guppy_basecaller demux. But I will extend it ASAP

**Comment by a-slide** [comment]
I updated the prototype to deal with different sorts of barcodes.
It is called Barcode_split and it's in the development "bam" branch
