### ISSUE TITLE
install pycoQC version v2.5.0.7 using Conda install

### ISSUE THREAD

**Issue by ktenpatel** [a-slide/pycoQC#91]
**Describe the bug**
I am trying to installing pycoQC v2.5.07 using conda.
pycoQC does install and works. However, the version that is installed is: pycoqc  aleg/noarch::pycoqc-2.3.1.6-py_0
Any suggestions?

I went to: https://anaconda.org/aleg/pycoqc
It shows the version should be  v2.5.0.7.  Unfortunately, v2.3.1.6 gets installed.
![pycoQC_Install](https://user-images.githubusercontent.com/7295137/65848661-1e14aa80-e315-11e9-8ffd-f0d292990841.jpg)

**Expected behavior**
Install latest version pycoQC v2.5.07
Commands:
conda create -n pycoQC python=3.6
conda install -c aleg pycoqc
conda update -c aleg pycoqc

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by a-slide** [comment]
Hi @ktenpatel,

It should have installed the last version. I don't really understand why it did not. There might be some lag in anaconda package updating.

Have you tried with `conda install -c aleg pycoqc=2.5.0.7`

Otherwise you can also try with pip as indicated in the documentation

**Comment by ktenpatel** [comment]
See below when attempting to run the command: conda install -c aleg pycoqc
=2.5.0.7

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: failed with repodata from current_repodata.json, will
retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed


UnsatisfiableError: The following specifications were found to be
incompatible with each other:



Package tqdm conflicts for:
pycoqc=2.5.0.7 -> tqdm=4.35.0
Package tk conflicts for:
python=3.6 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package pip conflicts for:
python=3.6 -> pip
Package libgcc-ng conflicts for:
python=3.6 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package numpy conflicts for:
pycoqc=2.5.0.7 -> numpy=1.17.1
Package h5py conflicts for:
pycoqc=2.5.0.7 -> h5py=2.9.0
Package jinja2 conflicts for:
pycoqc=2.5.0.7 -> jinja2=2.10.1
Package scipy conflicts for:
pycoqc=2.5.0.7 -> scipy=1.3.1
Package xz conflicts for:
python=3.6 -> xz[version='>=5.2.3,<6.0a0|>=5.2.4,<6.0a0']
Package ncurses conflicts for:
python=3.6 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
Package libstdcxx-ng conflicts for:
python=3.6 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package plotly conflicts for:
pycoqc=2.5.0.7 -> plotly=4.1.0
Package zlib conflicts for:
python=3.6 -> zlib[version='>=1.2.11,<1.3.0a0']
Package pandas conflicts for:
pycoqc=2.5.0.7 -> pandas=0.25.1
Package openssl conflicts for:
python=3.6 ->
openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1c,<1.1.2a']
Package pysam conflicts for:
pycoqc=2.5.0.7 -> pysam=0.15.3
Package libffi conflicts for:
python=3.6 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package readline conflicts for:
python=3.6 -> readline[version='7.*|>=7.0,<8.0a0']
Package sqlite conflicts for:
python=3.6 ->
sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.26.0,<4.0a0|>=3.29.0,<4.0a0']

**Comment by ktenpatel** [comment]
See message below when running command: conda install -c aleg pycoqc

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: failed with repodata from current_repodata.json,
will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ketal/anaconda3/envs/pycoQC

  added / updated specs:
    - pycoqc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.1.1d             |       h7b6447c_2         2.5 MB
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following NEW packages will be INSTALLED:

  asn1crypto         pkgs/main/linux-64::asn1crypto-0.24.0-py36_0
  attrs              pkgs/main/linux-64::attrs-19.1.0-py36_1
  blas               pkgs/main/linux-64::blas-1.0-mkl
  cffi               pkgs/main/linux-64::cffi-1.12.3-py36h2e261b9_0
  chardet            pkgs/main/linux-64::chardet-3.0.4-py36_1003
  cryptography       pkgs/main/linux-64::cryptography-2.7-py36h1ba5d50_0
  decorator          pkgs/main/linux-64::decorator-4.4.0-py36_1
  h5py               pkgs/main/linux-64::h5py-2.9.0-py36h7918eee_0
  hdf5               pkgs/main/linux-64::hdf5-1.10.4-hb1b8bf9_0
  idna               pkgs/main/linux-64::idna-2.8-py36_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2019.4-243
  ipython_genutils   pkgs/main/linux-64::ipython_genutils-0.2.0-py36_0
  jinja2             pkgs/main/linux-64::jinja2-2.10.1-py36_0
  jsonschema         pkgs/main/linux-64::jsonschema-3.0.2-py36_0
  jupyter_core       pkgs/main/noarch::jupyter_core-4.5.0-py_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  markupsafe         pkgs/main/linux-64::markupsafe-1.1.1-py36h7b6447c_0
  mkl                pkgs/main/linux-64::mkl-2019.4-243
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py36he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.0.14-py36ha843d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.0-py36hd6b4f25_0
  nbformat           pkgs/main/linux-64::nbformat-4.4.0-py36_0
  numpy              pkgs/main/linux-64::numpy-1.16.4-py36h7e9f1db_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.16.4-py36hde5b4d6_0
  pandas             pkgs/main/linux-64::pandas-0.24.2-py36he6710b0_0
  plotly             pkgs/main/noarch::plotly-3.10.0-py_0
  pycoqc             aleg/noarch::pycoqc-2.3.1.6-py_0
  pycparser          pkgs/main/linux-64::pycparser-2.19-py36_0
  pyopenssl          pkgs/main/linux-64::pyopenssl-19.0.0-py36_0
  pyrsistent         pkgs/main/linux-64::pyrsistent-0.15.4-py36h7b6447c_0
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py36_0
  python-dateutil    pkgs/main/linux-64::python-dateutil-2.8.0-py36_0
  pytz               pkgs/main/noarch::pytz-2019.2-py_0
  requests           pkgs/main/linux-64::requests-2.22.0-py36_0
  retrying           pkgs/main/linux-64::retrying-1.3.3-py36_2
  scipy              pkgs/main/linux-64::scipy-1.2.0-py36h7c811a0_0
  six                pkgs/main/linux-64::six-1.12.0-py36_0
  tqdm               pkgs/main/noarch::tqdm-4.32.1-py_0
  traitlets          pkgs/main/linux-64::traitlets-4.3.2-py36_0
  urllib3            pkgs/main/linux-64::urllib3-1.24.2-py36_0

The following packages will be UPDATED:

  openssl                                 1.1.1d-h7b6447c_1 -->
1.1.1d-h7b6447c_2

**Comment by ktenpatel** [comment]
After some effort, I was able to use Option 1: Installation with pip from pypi.
I now have v2.5.0.7 running.  The Basic usage is working fine and i am able to generate a html report.
I am now trying to use the Including Alignments information for a Bam file. 
I am having some trouble (IndexError: index 0 is out of bounds for axis 0 with size 0).  see attached file.  Can you suggest a possible fix?  I have generated a alignment using minmap2, sorted the bam file and indexed it.


![alignerror](https://user-images.githubusercontent.com/7295137/65929585-b754c700-e3d0-11e9-8099-01a82c7733b8.jpg)

**Comment by a-slide** [comment]
Hard to tell like this. Could you rerun in verbose mode and attach the standard error output in a text file ?

**Comment by ktenpatel** [comment]
You are correct. It was due to conda installation.  i reinstalled and it is performing as expected.
