### ISSUE TITLE
ZeroDivisionError with .bam input

### ISSUE THREAD

**Issue by moldovannorbert** [a-slide/pycoQC#92]
With option -a sample.bam I get an error in line 370 of pycoQC_parse.py
d["align_score"] = d["align_len"]/edit_dist
ZeroDivisionError: division by zero

sample.bam is the alignment produced by minimap2 -ax splice -Y -C5 and was sorted and indexed using samtools.

**Comment by a-slide** [comment]
Hi @moldovannorbert,
I noticed it and fixed that since the initial 2.5 release.
Just update your version and the error should hopefully be gone.

**Comment by moldovannorbert** [comment]
I installed it from the aleg channel on Conda. On the webpage it says v2.5.0.7 however v2.5.0.3 installs, which contains this bug. Odd behavior...

**Comment by a-slide** [comment]
I think conda has a bit of lag sometimes.
Pip normally works straight after a new version was published

**Comment by a-slide** [comment]
I assume it must be up to date by now
If not force the version using
 `conda install -c aleg pycoqc=2.5.0.10 `

or using pip
`pip install pycoQC==2.5.0.10`
